name: testbed

on: [push]

jobs:

  linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile testbed
      working-directory: build
      run: |
        cmake -DENTT_BUILD_TESTBED=ON ..
        make -j4

  windows:
    timeout-minutes: 15
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile testbed
      working-directory: build
      run: |
        cmake -DENTT_BUILD_TESTBED=ON ..
        cmake --build . -j 4

  macos:
    timeout-minutes: 15
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile testbed
      working-directory: build
      run: |
        cmake -DENTT_BUILD_TESTBED=ON ..
        make -j4
